title: Navigating Stories
email: k.pijpers@utwente.nl
description: This project aims to develop eScience technologies to advance multidisciplinary approaches of digital storytelling.
twitter_username: @verhalenlab
#github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
# remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
# Outputting
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

#footer:
#  name   : "First Lastname"
#  avatar : "/assets/images/bio-photo.jpg"
#  bio    : "My awesome biography constrained to a sentence or two goes here."
#  links:
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

author: 
  name: "Storylab"
  subtitle: "Department of Psychology, Health and Technology
            > University of Twente"
  avatar: 
  location: "Enschede, the Netherlands"
  links :
    - label: "Story Lab - University of Twente"
      icon: "fas fa-university"
      url: "https://www.utwente.nl/en/bms/ehealth/research/story-lab/"
    - label: "ResearchGate"
      icon: "fab fa-researchgate
      url: "https://www.researchgate.net/lab/StoryLab-Gerben-J-Westerhof"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/verhalenlab"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/navigating-stories/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
